[metadata]
version = "1.0"

[versions]
accessWidener = "2.1.0"
asm = "9.9.1"
vineFlower = "1.11.2"
ideaExt = "1.4.1"
indra = "4.0.0"
junit = "5.14.1"
mergeTool = "1.2.3"
mammoth = "1.5.0"

[libraries]
# gradle-plugin
accessWidener = { module = "net.fabricmc:access-widener", version.ref = "accessWidener" }
asm = { module = "org.ow2.asm:asm", version.ref = "asm" }
asm-commons = { module = "org.ow2.asm:asm-commons", version.ref = "asm" }
asm-util = { module = "org.ow2.asm:asm-util", version.ref = "asm" }
vineFlower = { module = "org.vineflower:vineflower", version.ref = "vineFlower" }
gson = { module = "com.google.code.gson:gson", version = "2.13.2" }
ideaExt = { module = "gradle.plugin.org.jetbrains.gradle.plugin.idea-ext:gradle-idea-ext", version.ref = "ideaExt" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher" }
mergeTool = { module = "net.minecraftforge:mergetool", version.ref = "mergeTool" }
shadowPlugin = { module = "com.gradleup.shadow:com.gradleup.shadow.gradle.plugin", version = "9.0.2" }
mammoth = { module = "net.kyori:mammoth", version.ref = "mammoth" }

[plugins]
blossom = { id = "net.kyori.blossom", version = "2.2.0" }
gradlePluginPublish = { id = "com.gradle.plugin-publish", version = "2.0.0" }
ideaExt = { id = "org.jetbrains.gradle.plugin.idea-ext", version.ref = "ideaExt" }
indra = { id = "net.kyori.indra", version.ref = "indra" }
indra-git = { id = "net.kyori.indra.git", version.ref = "indra" }
indra-licenserSpotless = { id = "net.kyori.indra.licenser.spotless", version.ref = "indra" }
indra-publishing = { id = "net.kyori.indra.publishing", version.ref = "indra" }
indra-publishing-gradlePlugin = { id = "net.kyori.indra.publishing.gradle-plugin", version.ref = "indra" }
indra-publishing-sonatype = { id = "net.kyori.indra.publishing.sonatype", version.ref = "indra" }
spotless = { id = "com.diffplug.spotless", version = "8.1.0" }
