# Making changes? https://github.com/nektos/act may help you test locally

name: Build, Test, and Deploy

on:
  push:
    branches: "**"
    tags-ignore: ["*"]
  pull_request:
  release:
    types: [released]

jobs:
  call-build:
    uses: SpongePowered/.github/.github/workflows/shared-ci.yaml@master
    with:
      publish_release_javadoc: false
      extra_gradle_publish_params: publishPlugins
    secrets: inherit
